### ISSUE TITLE
unable to write output

### ISSUE THREAD

**Issue by mmetois** [mauroalberti/VectorFieldCalc#1]
Dear Mauro, 
Tank you for developing the useful vectorfieldcalc tool for QGIS. I used to use it under Qgis 2.7 without issue. I am now using QGIS 3.6 and the tool is not working anymore. Giving it two rasters with east and north velocity components and asking for any of the output available, I get "Unable to write magn.asc" even if I do have the rights to do so. The file is created but empty. 
Any clue on what is going on ? 

I am running Ubuntu 18.04 with matplotlib 3 and Qgis 3.6
Thank for the help, 
Marianne

**Comment by mauroalberti** [comment]
Ciao Marianne,
could you please check whether the release candidate r2 (https://github.com/mauroalberti/VectorFieldCalc/releases/tag/v1.5.2rc2) solves the problem?
You should download the zip file, uncompress, rename the folder as "VectorFieldCalc" (i.e., removing the final part of the uncompressed folder name), zip again the renamed folder and update the plugin from the zip file.

Otherwise I could send you the zip file, just need your mail...

mauro

**Comment by mmetois** [comment]
Ok, it works now. Thank you for the quick answer. 
M.

**Comment by mauroalberti** [comment]
Thanks for the check.
mauro
